name = "hifz-companion-api"
main = "src/index.js"
compatibility_date = "2026-06-07"

# Ganti database_id setelah menjalankan:
# wrangler d1 create hifz-companion-db
[[d1_databases]]
binding = "DB"
database_name = "hifz-companion-db"
database_id = "4c00c0f4-a651-4363-90f1-48bf0126e752"

[[r2_buckets]]
binding = "SUBMISSIONS_BUCKET"
bucket_name = "hifz-companion-submissions"

[vars]
# Isi dengan domain GitHub Pages Bapak, contoh:
# ALLOWED_ORIGINS = "https://cakgup.github.io,https://cakgup.github.io/hifz-companion"
ALLOWED_ORIGINS = ""
